name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # Versi SDK disesuaikan ke versi yang lebih umum dan stabil
  # Sesuaikan ini jika Anda menggunakan versi Dart/Flutter yang sangat baru (misalnya ^3.0.0 atau ^3.4.0)
  # Menggunakan versi yang lebih umum untuk menghindari error jika Anda tidak memiliki versi 3.9.2
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  # Pastikan versi package sudah sesuai atau gunakan versi terbaru (misalnya versi terbaru dari pub.dev)
  uuid: ^4.3.1 
  flutter_colorpicker: ^1.1.0 
  file_picker: ^8.0.0
  intl: ^0.18.1 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Versi disesuaikan

flutter:
  uses-material-design: true

  # Perbaikan Indentasi untuk assets
  assets: 
    - images/